[features]
seeds = false
skip-lint = false
[programs.localnet]
twitter_solana = "E8whyuiegni6nsQYEg4GNtXyXrJK79tVwL37e34AwxPW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/vietvo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
